package com.example.bdmi.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class Dimens(
    // Spacing
    val small1: Dp,
    val small2: Dp,
    val small3: Dp,
    val medium1: Dp,
    val medium2: Dp,
    val medium3: Dp,
    val large1: Dp,
    val large2: Dp,
    val large3: Dp,

    // Icon sizes
    val iconTiny: Dp,
    val iconSmall: Dp,
    val iconMedium: Dp,
    val iconLarge: Dp,
    val iconHuge: Dp,

    // Button dimensions
    val buttonHeightSmall: Dp,
    val buttonHeightMedium: Dp,
    val buttonHeightLarge: Dp,
    val buttonWidthSmall: Dp,
    val buttonWidthMedium: Dp,
    val buttonWidthLarge: Dp,

    // Logo and images
    val logoSizeSmall: Dp,
    val logoSizeMedium: Dp,
    val logoSizeLarge: Dp,
    val posterSize: Dp,
    val noPosterIconSize: Dp,
    val backdropHeight: Dp,

    // Specific UI components
    val topBarHeight: Dp,
    val bottomBarHeight: Dp,
    val topBarIconSize: Dp,
    val notificationBadgeSize: Dp,

    // Movie Detail
    val topBoxHeight: Dp,
    val reviewHeight: Dp,
    val carouselDotSize: Dp,
    val personRowHeight: Dp,
    val bottomColumnHeight: Dp,
    val countryRowHeight: Dp,
    val exploreRowHeight: Dp,

    // Ratings stuff
    val movieRowWidth: Dp,
    val movieRowHeight: Dp,
    val placeholderWidth: TextUnit,
    val placeholderHeight: TextUnit,

    // Detailed screens
    val studioLogoSize: Dp,
    val parentLogoSize: Dp,

    // Misc
    val friendProfileSize: Dp,
    val reviewCardHeight: Dp,
    val profileSize: Dp,
    val profileBorder: Dp,
    val wahteverDaHellThisIsRowHeight: Dp
)

val MediumDimens = Dimens(
    // Spacing
    small1 = 2.dp,
    small2 = 4.dp,
    small3 = 8.dp,
    medium1 = 10.dp,
    medium2 = 12.dp,
    medium3 = 16.dp,
    large1 = 20.dp,
    large2 = 24.dp,
    large3 = 32.dp,

    // Icon sizes
    iconTiny = 14.dp,
    iconSmall = 20.dp,
    iconMedium = 30.dp,
    iconLarge = 40.dp,
    iconHuge = 50.dp,

    // Button dimensions
    buttonHeightSmall = 30.dp,
    buttonHeightMedium = 40.dp,
    buttonHeightLarge = 56.dp,
    buttonWidthSmall = 100.dp,
    buttonWidthMedium = 150.dp,
    buttonWidthLarge = 200.dp,

    // Logo and images
    logoSizeSmall = 42.dp,
    logoSizeMedium = 75.dp,
    logoSizeLarge = 120.dp,
    posterSize = 225.dp,
    noPosterIconSize = 50.dp,
    backdropHeight = 180.dp,

    // Specific UI components
    topBarHeight = 100.dp,
    bottomBarHeight = 75.dp,
    topBarIconSize = 30.dp,
    notificationBadgeSize = 18.dp,

    // Movie Detail
    topBoxHeight = 420.dp,
    reviewHeight = 100.dp,
    carouselDotSize = 10.dp,
    personRowHeight = 75.dp,
    bottomColumnHeight = 550.dp,
    countryRowHeight = 25.dp,
    exploreRowHeight = 200.dp,

    // Ratings stuff
    movieRowWidth = 100.dp,
    movieRowHeight = 150.dp,
    placeholderWidth = 15.sp,
    placeholderHeight = 18.sp,

    // Detailed screens
    studioLogoSize = 150.dp,
    parentLogoSize = 50.dp,

    // Misc
    friendProfileSize = 90.dp,
    reviewCardHeight = 140.dp,
    profileSize = 250.dp,
    profileBorder = 300.dp,
    wahteverDaHellThisIsRowHeight = 65.dp
)

// Dimens scaling generated by Deepseek AI.
val LargeDimens = Dimens(
    // Spacing (1.25x scale)
    small1 = 2.5.dp,
    small2 = 5.dp,
    small3 = 10.dp,
    medium1 = 12.5.dp,
    medium2 = 15.dp,
    medium3 = 20.dp,
    large1 = 25.dp,
    large2 = 30.dp,
    large3 = 40.dp,

    // Icon sizes
    iconTiny = 17.5.dp,
    iconSmall = 25.dp,
    iconMedium = 37.5.dp,
    iconLarge = 50.dp,
    iconHuge = 62.5.dp,

    // Button dimensions
    buttonHeightSmall = 37.5.dp,
    buttonHeightMedium = 50.dp,
    buttonHeightLarge = 70.dp,
    buttonWidthSmall = 125.dp,
    buttonWidthMedium = 187.5.dp,
    buttonWidthLarge = 250.dp,

    // Logo and images
    logoSizeSmall = 52.5.dp,
    logoSizeMedium = 93.75.dp,
    logoSizeLarge = 150.dp,
    posterSize = 281.25.dp,
    noPosterIconSize = 62.5.dp,
    backdropHeight = 225.dp,

    // Specific UI components
    topBarHeight = 125.dp,
    bottomBarHeight = 93.75.dp,
    topBarIconSize = 37.5.dp,
    notificationBadgeSize = 22.5.dp,

    // Movie Detail
    topBoxHeight = 525.dp,
    reviewHeight = 125.dp,
    carouselDotSize = 12.5.dp,
    personRowHeight = 93.75.dp,
    bottomColumnHeight = 687.5.dp,
    countryRowHeight = 31.25.dp,
    exploreRowHeight = 250.dp,

    // Ratings stuff
    movieRowWidth = 125.dp,
    movieRowHeight = 187.5.dp,
    placeholderWidth = 18.75.sp,
    placeholderHeight = 22.5.sp,

    // Detailed screens
    studioLogoSize = 187.5.dp,
    parentLogoSize = 62.5.dp,

    // Misc
    friendProfileSize = 112.5.dp,
    reviewCardHeight = 175.dp,
    profileSize = 312.5.dp,
    profileBorder = 375.dp,
    wahteverDaHellThisIsRowHeight = 81.25.dp
)

val ExpandedDimens = Dimens(
    // Spacing (1.5x scale)
    small1 = 3.dp,
    small2 = 6.dp,
    small3 = 12.dp,
    medium1 = 15.dp,
    medium2 = 18.dp,
    medium3 = 24.dp,
    large1 = 30.dp,
    large2 = 36.dp,
    large3 = 48.dp,

    // Icon sizes
    iconTiny = 21.dp,
    iconSmall = 30.dp,
    iconMedium = 45.dp,
    iconLarge = 60.dp,
    iconHuge = 75.dp,

    // Button dimensions
    buttonHeightSmall = 45.dp,
    buttonHeightMedium = 60.dp,
    buttonHeightLarge = 84.dp,
    buttonWidthSmall = 150.dp,
    buttonWidthMedium = 225.dp,
    buttonWidthLarge = 300.dp,

    // Logo and images
    logoSizeSmall = 63.dp,
    logoSizeMedium = 112.5.dp,
    logoSizeLarge = 180.dp,
    posterSize = 337.5.dp,
    noPosterIconSize = 75.dp,
    backdropHeight = 270.dp,

    // Specific UI components
    topBarHeight = 150.dp,
    bottomBarHeight = 112.5.dp,
    topBarIconSize = 45.dp,
    notificationBadgeSize = 27.dp,

    // Movie Detail
    topBoxHeight = 630.dp,
    reviewHeight = 150.dp,
    carouselDotSize = 15.dp,
    personRowHeight = 112.5.dp,
    bottomColumnHeight = 825.dp,
    countryRowHeight = 37.5.dp,
    exploreRowHeight = 300.dp,

    // Ratings stuff
    movieRowWidth = 150.dp,
    movieRowHeight = 225.dp,
    placeholderWidth = 22.5.sp,
    placeholderHeight = 27.sp,

    // Detailed screens
    studioLogoSize = 225.dp,
    parentLogoSize = 75.dp,

    // Misc
    friendProfileSize = 135.dp,
    reviewCardHeight = 210.dp,
    profileSize = 375.dp,
    profileBorder = 450.dp,
    wahteverDaHellThisIsRowHeight = 97.5.dp
)