package com.example.bdmi.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

// TODO: Add typography for Compact devices

val MediumTypography = Typography(
    // TODO: Customize letter spacing, font style/family, etc.
    displayLarge = TextStyle(
        fontSize = 48.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 56.sp
    ),
    displayMedium = TextStyle(
        fontSize = 40.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 48.sp
    ),
    displaySmall = TextStyle(
        fontSize = 34.sp,
        fontWeight = FontWeight.Bold,
        lineHeight = 40.sp
    ),

    headlineLarge = TextStyle(
        fontSize = 30.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 36.sp
    ),
    headlineMedium = TextStyle(
        fontSize = 24.sp,
        fontWeight = FontWeight.SemiBold,
        lineHeight = 32.sp
    ),
    headlineSmall = TextStyle(
        fontSize = 20.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 28.sp,
        letterSpacing = 0.5.sp
    ),

    titleLarge = TextStyle(
        fontSize = 18.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 24.sp
    ),
    titleMedium = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 22.sp
    ),
    titleSmall = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 20.sp
    ),

    bodyLarge = TextStyle(
        fontSize = 16.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 24.sp,
        letterSpacing = 1.sp
    ),
    bodyMedium = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 20.sp,
        letterSpacing = 2.sp
    ),
    bodySmall = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.Normal,
        lineHeight = 16.sp
    ),

    labelLarge = TextStyle(
        fontSize = 14.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 20.sp
    ),
    labelMedium = TextStyle(
        fontSize = 12.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 16.sp
    ),
    labelSmall = TextStyle(
        fontSize = 10.sp,
        fontWeight = FontWeight.Medium,
        lineHeight = 14.sp
    )
)

// Font scaling generated by Deepseek AI.
val LargeTypography = Typography(
    displayLarge = TextStyle(
        fontSize = 55.sp,  // 48 * 1.15
        fontWeight = FontWeight.Bold,
        lineHeight = 64.sp  // 56 * 1.15
    ),
    displayMedium = TextStyle(
        fontSize = 46.sp,  // 40 * 1.15
        fontWeight = FontWeight.Bold,
        lineHeight = 55.sp  // 48 * 1.15
    ),
    displaySmall = TextStyle(
        fontSize = 39.sp,  // 34 * 1.15
        fontWeight = FontWeight.Bold,
        lineHeight = 46.sp  // 40 * 1.15
    ),

    headlineLarge = TextStyle(
        fontSize = 34.sp,  // 30 * 1.15
        fontWeight = FontWeight.SemiBold,
        lineHeight = 41.sp  // 36 * 1.15
    ),
    headlineMedium = TextStyle(
        fontSize = 27.sp,  // 24 * 1.15
        fontWeight = FontWeight.SemiBold,
        lineHeight = 37.sp  // 32 * 1.15
    ),
    headlineSmall = TextStyle(
        fontSize = 23.sp,  // 20 * 1.15
        fontWeight = FontWeight.Medium,
        lineHeight = 32.sp,  // 28 * 1.15
        letterSpacing = 0.6.sp  // 0.5 * 1.15
    ),

    titleLarge = TextStyle(
        fontSize = 21.sp,  // 18 * 1.15
        fontWeight = FontWeight.Medium,
        lineHeight = 28.sp  // 24 * 1.15
    ),
    titleMedium = TextStyle(
        fontSize = 18.sp,  // 16 * 1.15
        fontWeight = FontWeight.Medium,
        lineHeight = 25.sp  // 22 * 1.15
    ),
    titleSmall = TextStyle(
        fontSize = 16.sp,  // 14 * 1.15
        fontWeight = FontWeight.Medium,
        lineHeight = 23.sp  // 20 * 1.15
    ),

    bodyLarge = TextStyle(
        fontSize = 18.sp,  // 16 * 1.15
        fontWeight = FontWeight.Normal,
        lineHeight = 28.sp,  // 24 * 1.15
        letterSpacing = 1.15.sp  // 1 * 1.15
    ),
    bodyMedium = TextStyle(
        fontSize = 16.sp,  // 14 * 1.15
        fontWeight = FontWeight.Normal,
        lineHeight = 23.sp,  // 20 * 1.15
        letterSpacing = 2.3.sp  // 2 * 1.15
    ),
    bodySmall = TextStyle(
        fontSize = 14.sp,  // 12 * 1.15
        fontWeight = FontWeight.Normal,
        lineHeight = 18.sp  // 16 * 1.15
    ),

    labelLarge = TextStyle(
        fontSize = 16.sp,  // 14 * 1.15
        fontWeight = FontWeight.Medium,
        lineHeight = 23.sp  // 20 * 1.15
    ),
    labelMedium = TextStyle(
        fontSize = 14.sp,  // 12 * 1.15
        fontWeight = FontWeight.Medium,
        lineHeight = 18.sp  // 16 * 1.15
    ),
    labelSmall = TextStyle(
        fontSize = 11.sp,  // 10 * 1.15
        fontWeight = FontWeight.Medium,
        lineHeight = 16.sp  // 14 * 1.15
    )
)

val ExpandedTypography = Typography(
    displayLarge = TextStyle(
        fontSize = 60.sp,  // 48 * 1.25
        fontWeight = FontWeight.Bold,
        lineHeight = 70.sp  // 56 * 1.25
    ),
    displayMedium = TextStyle(
        fontSize = 50.sp,  // 40 * 1.25
        fontWeight = FontWeight.Bold,
        lineHeight = 60.sp  // 48 * 1.25
    ),
    displaySmall = TextStyle(
        fontSize = 42.sp,  // 34 * 1.25
        fontWeight = FontWeight.Bold,
        lineHeight = 50.sp  // 40 * 1.25
    ),

    headlineLarge = TextStyle(
        fontSize = 38.sp,  // 30 * 1.25
        fontWeight = FontWeight.SemiBold,
        lineHeight = 45.sp  // 36 * 1.25
    ),
    headlineMedium = TextStyle(
        fontSize = 30.sp,  // 24 * 1.25
        fontWeight = FontWeight.SemiBold,
        lineHeight = 40.sp  // 32 * 1.25
    ),
    headlineSmall = TextStyle(
        fontSize = 25.sp,  // 20 * 1.25
        fontWeight = FontWeight.Medium,
        lineHeight = 35.sp,  // 28 * 1.25
        letterSpacing = 0.6.sp  // 0.5 * 1.25
    ),

    titleLarge = TextStyle(
        fontSize = 23.sp,  // 18 * 1.25
        fontWeight = FontWeight.Medium,
        lineHeight = 30.sp  // 24 * 1.25
    ),
    titleMedium = TextStyle(
        fontSize = 20.sp,  // 16 * 1.25
        fontWeight = FontWeight.Medium,
        lineHeight = 28.sp  // 22 * 1.25
    ),
    titleSmall = TextStyle(
        fontSize = 18.sp,  // 14 * 1.25
        fontWeight = FontWeight.Medium,
        lineHeight = 25.sp  // 20 * 1.25
    ),

    bodyLarge = TextStyle(
        fontSize = 20.sp,  // 16 * 1.25
        fontWeight = FontWeight.Normal,
        lineHeight = 30.sp,  // 24 * 1.25
        letterSpacing = 1.25.sp  // 1 * 1.25
    ),
    bodyMedium = TextStyle(
        fontSize = 18.sp,  // 14 * 1.25
        fontWeight = FontWeight.Normal,
        lineHeight = 25.sp,  // 20 * 1.25
        letterSpacing = 2.5.sp  // 2 * 1.25
    ),
    bodySmall = TextStyle(
        fontSize = 15.sp,  // 12 * 1.25
        fontWeight = FontWeight.Normal,
        lineHeight = 20.sp  // 16 * 1.25
    ),

    labelLarge = TextStyle(
        fontSize = 18.sp,  // 14 * 1.25
        fontWeight = FontWeight.Medium,
        lineHeight = 25.sp  // 20 * 1.25
    ),
    labelMedium = TextStyle(
        fontSize = 15.sp,  // 12 * 1.25
        fontWeight = FontWeight.Medium,
        lineHeight = 20.sp  // 16 * 1.25
    ),
    labelSmall = TextStyle(
        fontSize = 12.sp,  // 10 * 1.25
        fontWeight = FontWeight.Medium,
        lineHeight = 18.sp  // 14 * 1.25
    )
)